apiVersion: v1
kind: LimitRange
metdata:
  name: cpu-resource-constarint
spec:
  limits:
    default: # Limit
      cpu: 500m
    defaultRequest: # FRequest
      cpu: 500m
    max: # limit
      cpu: 1
    min: # request
      cpu: 100m
    type: container