apiVersion: apps/v1
kind: Deployment
metadata:
  name: red
  labels:
    color: red
spec:
  replicas: 2
  selector:
    matchLabels:
      color: red
  template:
    metadata:
      name: red
      labels:
        color: red
    spec:
      containers:
        - image: nginx
          name: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: In
                    values:
                      - node.kubernetes.io/exclude-from-external-load-balancers=