apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 # port on the pod
      targetPort: 80 # port on the service
      nodePort: 30004 # port on the node - minikube
  selector:
    app: myapp